django_project/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views.api_view import Docs
from .views.facilities import FacilitiesApiView
from .views.locality_create import LocalityCreateApiView
from .views.locality_detail import LocalityDetailApiView
from .views.locality_search import LocalitySearchApiView
from .views.locality_synonym import LocalitySynonymApiView

urlpatterns = patterns(
    '',
    url(r'^v1/healthsites/facilities', FacilitiesApiView.as_view(), name='api_facilities'),
    url(
        r'^v1/healthsites/search', LocalitySearchApiView.as_view(), name='api_search_localities'
    ),
    url(
        r'^v1/healthsites/facility/details', LocalityDetailApiView.as_view(),
        name='api_locality_detail'
    ),
    url(
        r'^v1/healthsites/facility/synonyms', LocalitySynonymApiView.as_view(),
        name='api_locality_synonyms'
    ),
    url(
        r'^v1/healthsites/facility/add', LocalityCreateApiView.as_view(),
        name='api_search_localities'
    ),
    url(r'^v1', Docs.as_view(), name='docs'),
)

django_project/localities/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views import (
    DataLoaderView, GetUserUpdates, LocalitiesLayer, LocalityInfo, LocalityReportDuplicate
)

urlpatterns = patterns(
    '',
    url(
        r'^localities.json$', LocalitiesLayer.as_view(),
        name='localities'
    ),
    url(
        r'^localities/(?P<uuid>\w{32})$', LocalityInfo.as_view(),
        name='locality-info'
    ),
    url(
        r'^localities/(?P<uuid>\w{32})/(?P<changes>[0-9].*)$', LocalityInfo.as_view(),
        name='locality-info-history'
    ),
    url(
        r'^localities/edit$', 'localities.views.locality_edit_view',
        name='locality-edit'
    ),
    url(
        r'^localities/create$', 'localities.views.locality_create_view',
        name='locality-create'
    ),

    url(
        r'^search/localities/name$',
        'localities.views.search_locality_by_name',
        name='locality-name-search'
    ),

    url(
        r'^search/cities/name',
        'localities.views.search_cities_by_name',
        name='cities-name-search'
    ),

    url(
        r'^countries$',
        'localities.views.search_countries',
        name='countries'
    ),

    url(
        r'^search/localities/country$',
        'localities.views.search_locality_by_country',
        name='locality-country-search'
    ),

    url(
        r'^locality/updates$',
        'localities.views.get_locality_update',
        name='locality-updates'
    ),

    url(
        r'^upload-form$', DataLoaderView.as_view(), name='upload-form'
    ),

    # url(r'^search$', SearchView.as_view(), name='search')
    # -------------------------------------------------------------------------
    # MASTERIZATION URLS
    # -------------------------------------------------------------------------
    url(
        r'^report$',
        LocalityReportDuplicate.as_view(),
        name='api_locality_synonyms'
    ),
    url(
        r'^user/updates/$', GetUserUpdates.as_view(), name='user-updates'
    ),
)

django_project/localities/forms.py
# -*- coding: utf-8 -*-
import logging

import django.forms as forms
from django.forms import models

from social_users.models import Organisation

from .models import DataLoader, Domain
from .utils import render_fragment

LOG = logging.getLogger(__name__)


class DomainModelForm(forms.ModelForm):
    """
    Used in django admin

    Special validation rules for template_fragment field
    """

    class Meta:
        model = Domain
        fields = ('name', 'description', 'template_fragment')

    def clean_template_fragment(self):
        try:
            render_fragment(self.cleaned_data['template_fragment'], {})
        except Exception as e:
            raise forms.ValidationError(
                'Template Syntax Error: {}'.format(e.message)
            )

        return self.cleaned_data['template_fragment']


class DomainForm(forms.Form):
    """
    Used when creating a new Locality

    Form will dynamically add every specification of an attribute as a simple
    CharField
    """

    lon = forms.FloatField()
    lat = forms.FloatField()

    def __init__(self, *args, **kwargs):
        # pop arguments which are not form fields
        domain = kwargs.pop('domain')

        super(DomainForm, self).__init__(*args, **kwargs)

        # populate form with attribute specifications
        for spec in domain.specification_set.select_related('attribute'):
            field = forms.CharField(
                label=spec.attribute.key, required=spec.required
            )
            self.fields[spec.attribute.key] = field


class LocalityForm(forms.Form):
    """
    Used when updating a Locality

    Form will dynamically add every specification of an attribute as a simple
    CharField, and prefill it with initial values
    """

    lon = forms.FloatField()
    lat = forms.FloatField()

    def __init__(self, *args, **kwargs):
        # pop arguments which are not form fields
        locality = kwargs.pop('locality')

        tmp_initial_data = {
            'lon': locality.geom.x, 'lat': locality.geom.y
        }

        # Locality forms are special as they automatically collect initial data
        # based on the actual models
        for value in locality.value_set.select_related('specification').all():
            tmp_initial_data.update({
                value.specification.attribute.key: value.data
            })

        # set initial form data
        kwargs.update({'initial': tmp_initial_data})

        super(LocalityForm, self).__init__(*args, **kwargs)

        for spec in (
                locality.domain.specification_set.select_related('attribute')):
            field = forms.CharField(
                label=spec.attribute.key, required=spec.required
            )
            self.fields[spec.attribute.key] = field
            self.fields[spec.attribute.key].widget.attrs.update(
                {'class': 'form-control'})


class DataLoaderForm(models.ModelForm):
    """Form for DataLoader.
    """

    class Meta:
        model = DataLoader
        fields = (
            'json_concept_mapping',
            'csv_data',
            'data_loader_mode',
        )

    json_concept_mapping = forms.FileField(
        widget=forms.FileInput()
    )

    csv_data = forms.FileField(
        widget=forms.FileInput()
    )

    data_loader_mode = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=DataLoader.DATA_LOADER_MODE_CHOICES,
        initial=DataLoader.REPLACE_DATA_CODE,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DataLoaderForm, self).__init__(*args, **kwargs)

        if self.user.is_staff:
            self.fields['organisations'] = forms.ChoiceField(
                choices=[
                    (org.id, org.name) for org in Organisation.objects.all().order_by('name')
                ]
            )
        else:
            self.fields['organisations'] = forms.ChoiceField(
                choices=[
                    (org.id, org.name) for org in (
                        Organisation.objects.filter(trusted_users__user=self.user)
                        .order_by('name')
                    )
                ]
            )

    def save(self, commit=True):
        """Save method.
        """
        data = self.cleaned_data
        data_loader = super(DataLoaderForm, self).save(commit=False)
        data_loader.author = self.user
        data_loader.applied = False
        data_loader.organisation_name = Organisation.objects.get(id=data['organisations']).name
        if commit:
            data_loader.save()
        return data_loader


class SearchForm(forms.Form):
    """Form for search"""
    LOCALITY_CODE = 1
    GEONAME_CODE = 2

    MODE_CHOICES = (
        (LOCALITY_CODE, 'Healthsites'),
        (GEONAME_CODE, 'Place'),
    )

    search = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(
            attrs={
                # 'class': 'form-control',
                'placeholder': 'Search'
            }),
    )

    mode = forms.ChoiceField(
        label='',
        # widget=forms.RadioSelect(
        #     attrs={'class': 'form-control'}),
        choices=MODE_CHOICES,
        initial=GEONAME_CODE,
    )

django_project/localities/templates/dataloaderform.html
{% extends 'base.html' %}
{% load pipeline %}
{% load static %}

{% block content %}
    <section class="white container">

        {% if upload_message %}
            <div class="alert alert-success">
                {{ upload_message }}
            </div>
        {% endif %}

        <h4 class="modal-title">Healthsites - Data Loader</h4>
        <form id="data-loader-form" class="" action="/upload-form" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>

            <input type="submit" class="btn btn-primary" value="Submit"/>
        </form>

    </section>
{% endblock content %}

django_project/localities/templates/search.html
{% extends 'base.html' %}

{% block header %}

{% endblock header %}

{% block title %}Healthsites{% endblock %}

{% block content %}

    <h1 id="title">Search</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Search"/>
    </form>

{% endblock content %}

{% block extra_js %}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            $(function () {
                function log(message) {
                    alert(message);
                }

                $("#id_search").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: "http://gd.geobytes.com/AutoCompleteCity",
                            dataType: "jsonp",
                            data: {
                                q: request.term
                            },
                            success: function (data) {
                                response(data);
                            }
                        });
                    },
                    minLength: 3,
                    select: function (event, ui) {
{#                        var geocoder = new google.maps.Geocoder();#}
{#                        geocoder.geocode({'address': $('#id_geoname').val()},#}
{#                                function (results, status) {#}
{#                                    if (status == google.maps.GeocoderStatus.OK) {#}
{#                                        var lat = results[0].geometry.location.lat();#}
{#                                        var lng = results[0].geometry.location.lng();#}
{##}
{#                                        log(ui.item ?#}
{#                                        "Selected: " + ui.item.label + '(' + lat + ',' + lng + ')':#}
{#                                        "Nothing selected, input was " + this.value);#}
{##}
{#                                    } else {#}
{#                                        alert("Something got wrong with location " +#}
{#                                                "autocomplete." + status);#}
{#                                    }#}
{#                                });#}

                    },
                    open: function () {
                        $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
                    },
                    close: function () {
                        $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
                    }
                });
            });
        });
    </script>
{% endblock extra_js %}

django_project/localities/templates/updateform.html
<!-- Nav tabs -->
<form class="form-horizontal" role="form">
<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="active"><a href="#filled" role="tab" data-toggle="tab">Filled attributes</a></li>
  <li role="presentation"><a href="#empty-form-tab" role="tab" data-toggle="tab">Empty attributes</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="filled">
        {% for elem in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label">{{ elem.label }}</label>
            <div class="col-sm-10">
                {{ elem }}
            </div>
        </div>
        {% endfor %}
    </div>
    <div role="tabpanel" class="tab-pane" id="empty-form-tab">
    </div>
</div>
</form>